### ISSUE TITLE
Creating services generates network connection loss

### ISSUE THREAD

**Issue by leonardinux** [urlgrey/hsmm-pi#24]
My Raspberry is already on the net for days. I create a service to access an http page on a PC inside the local network. After the restart any node in the network is detected.
To fix the raspberry again and let it see the network I had to do:

<code>cd ~/hsmm-pi/
sudo cp src/var/data/hsmm-pi/hsmm-pi.sqlite /var/data/hsmm-pi/</code>

and redo the GUI setup.

<i>73 de Leo IZ5FSA</i>

**Comment by argilo** [comment]
Services appear to be working fine in HSMM-Pi 0.8.0.
