### ISSUE TITLE
Web interface broken on Ubuntu 13.04 and 13.10

### ISSUE THREAD

**Issue by kevinelliott** [urlgrey/hsmm-pi#26]
On fresh and updated Ubuntu 13.10 and 13.04, hsmm-pi doesn't work out of the box. Web interface doesn't display assets, and login page is 404.

**Comment by argilo** [comment]
Ubuntu 13.04 and 13.10 are obsolete, and https://github.com/urlgrey/hsmm-pi/issues/32 appears to cover the same issue. Closing.
