### ISSUE TITLE
Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by khancyr** [urlgrey/hsmm-pi#32]
There is a problem in the installation (at least on Beaglebone black with ubuntu 14.04) with CakePHP

Starting to download CakePHP-2.5.2.tgz (792,150 bytes)
.............................................................................................................................................................done: 792,150 bytes
could not extract the package.xml file from "/build/buildd/php5-5.5.9+dfsg/pear-build-download/CakePHP-2.5.2.tgz"
Download of "cakephp/CakePHP" succeeded, but it is not a valid package archive
Error: cannot download "cakephp/CakePHP"
Download failed
install failed

--------

A solution to get it working is  to use -Z argument in pear install
sudo pear install -Z cakephp/CakePHP-2.4.10

It will use non compressed package and it works!

**Comment by argilo** [comment]
The installer now uses Composer instead of PEAR, so this shouldn't be an issue anymore.
