### ISSUE TITLE
Web interface access

### ISSUE THREAD

**Issue by sv1iw** [urlgrey/hsmm-pi#36]
Hi all
new to this, followed the instructions to get hsmm on a raspberry pi but after finished I have not access to the web interface. Say I am not aloud to have access on index.php. I tried a few things permissions wise but does not seem to help. Suggestions anyone? 

Thanks Manos SV1IW

**Comment by virtualdxs** [comment]
Don't run the install script as root.

**Comment by virtualdxs** [comment]
I had the same problem until I did it again on a fresh install w/o root.
