### ISSUE TITLE
Alfa AWUS036H compatibility with 0.4.0

### ISSUE THREAD

**Issue by SDreher71** [urlgrey/hsmm-pi#38]
The Alfa AWUS036H wifi adapter was working with HSMM-Pi that I cloned back in July, and was able to work with Linksys and Ubiquiti nodes. I recenly did a fresh install after upgrading Linksys and Ubiquiti nodes to BBHN v3. The new install works fine with a wifi adapter from Adafruit, but the Alfa unit now doesn't work. It seems to have trouble setting to Ad Hoc mode. When I try to reset the wlan0 interface, I get a message "Device or Resource busy."

I tried going back to HSMM-Pi v0.3.0
    -the Alfa adapter works, sees and is seen by the other nodes, but 
    -can't actually communicate (services on other nodes don't work, RasPi node services don't work on other nodes)

I tried installing with tags/v0.4.0
    -initially the Alfa would not function
    -after adding "auto eth0" to /etc/network/interfaces and restarting the networking service, the Alfa adapter works (sees/is seen by other nodes)
    -after a reboot, however, the Alfa adapter again fails. If I take out "auto eth0", restart networking, the add "auto eth0" back, and again restart the networking service, it works.
    - I haven't had time yet to determine if mesh services work between nodes with the v0.4.0 node working.

Any thoughts?

**Comment by SDreher71** [comment]
I've found a workaround posted by +Jon A on the Google+ community. Run this script at startup:
-------------------------
#!/bin/bash
service ifplugd stop
ifconfig wlan0 down
iwconfig wlan0 txpower 30 #if you want to use 1W of power
iwconfig wlan0 mode Ad-Hoc
iwconfig wlan0 essid BroadbandHamnet-20-v3 #or whatever the SSID for your mesh is
ifconfig wlan0 up
service ifplugd start
-------------------------
Now the RasPi nodes start and connect to each other and to Linksys and Ubiquiti nodes without any trouble.

**Comment by argilo** [comment]
Try with the latest hsmm-pi. I modified the install script to remove ifplugd, which was interfering with olsrd.

**Comment by argilo** [comment]
Closing, as this was most likely fixed by https://github.com/urlgrey/hsmm-pi/pull/42.
