### ISSUE TITLE
git clone routine not able to find bbhn packages

### ISSUE THREAD

**Issue by John-Richards** [urlgrey/hsmm-pi#39]
When installing  through the install.sh routine an error occurs when it attempts to run "git clone git://ubnt.hsmm-mesh.org/bbhn_packages". The error is a failure to connect to the url... I checked, it no longer exists. It doesn't appear that they use any of the same directory structures at broadband-hamnet.org anymore. Any suggestions?
John, KY8T

**Comment by John-Richards** [comment]
Problem solved. BEFORE!!! running install. sh you MUST edit the line calling the bbhm pckages from:
git clone git://ubnt.hsmm-mesh.org/bbhn_packages
To:
git clone git://ubnt.broadband-hamnet.org/bbhn_packages

**Comment by argilo** [comment]
Recently removed the dependency on bbhn_packages completely, as the patch I was pulling from that repo is no longer needed. So this shouldn't be an issue anymore.
