### ISSUE TITLE
Broadband Hamnet version 3

### ISSUE THREAD

**Issue by virtualdxs** [urlgrey/hsmm-pi#52]
Broadband Hamnet version 3 was released for all hardware, but it's not compatible with v2 or v1. Would it be possible to get HSMM-Pi to work with BBHN3?

**Comment by virtualdxs** [comment]
Label broadband-hamnet-compatibility should be assigned but I don't know how

**Comment by virtualdxs** [comment]
I'd be very glad to help if I knew how, but I have no idea where to start.

**Comment by argilo** [comment]
I haven't had any trouble using hsmm-pi with BBHN 3. Have you run into problems?

**Comment by virtualdxs** [comment]
No, but I assumed that it was incompatible seeing as it hasn't been worked on in a month and the site says 3.x is incompatible with 2.x, which is why I haven't upgraded my Linksys nodes. So you're saying you have used it with 3.x and have not had problems?

**Comment by argilo** [comment]
No trouble at all. There are several hsmm-pi nodes running on the local BBHN v3 mesh.

**Comment by virtualdxs** [comment]
Alrighty then. I'm really surprised, but if it works, it works. Thanks! Closing the issue.
