### ISSUE TITLE
Adding Service

### ISSUE THREAD

**Issue by ghinton77** [urlgrey/hsmm-pi#62]
Is there a tutorial or Help page showing how and what to put in the Services Adding page to make it work?
I tried to add a Service.  It shows up on the HSMM-Pi node, but not on the Linksys nodes in the network.
How do I redirect it to port 80 and a path other than /var/www ?
It only gives me a choice of TCP or UDP.  What if I want 'http' ?  Is this the same as one of those choices?
Gary

**Comment by argilo** [comment]
@ghinton77 There was a bug preventing services from appearing on the rest of the network, which I've fixed in version 0.7.0. I also added support for setting a path. To use the http protocol for the service, put that in the "Service Protocol Name" field. Hope that helps!
