### ISSUE TITLE
Jessie image does not boot on Pi Model B (old 2 USB port Model)

### ISSUE THREAD

**Issue by va3rjs** [urlgrey/hsmm-pi#65]
anyone come across this issue.....the image boots fine on the newer version......

Any ideas?

do I need to adjust  some files once the image is installed to the SD?

B

**Comment by SalvorinFex** [comment]
Howdy, You may have to perform a:  `sudo apt-get rpi-update`

Just a guess but it may work.

**Comment by argilo** [comment]
The latest Raspbian Jessie image boots fine for me on an old Model B. I'm closing this issue, as it relates to Raspbian and not HSMM-Pi.

**Comment by va3rjs** [comment]
Ok close away

Thanks
B
