### ISSUE TITLE
Service announcements 

### ISSUE THREAD

**Issue by mathisono** [urlgrey/hsmm-pi#67]
SO I can only define ports Ie http://KJ6DZB-4.local.mesh:8080

I cant announce http://KJ6DZB-4.local.mesh:8080/meshchat 

Ideas ?

**Comment by mathisono** [comment]
the services are not showing up in the rest of the aredn mesh

**Comment by argilo** [comment]
I haven't used that feature before. Just tried it and got the same result as you. I'll dig into it soon.

**Comment by mathisono** [comment]
any update... I will check out the new update but. I want to sort this out... I will didg around in the olsrd config for Service announcements. The HSMM-pi web page shows the Service announcements but its not going out to the mesh. ;-(

**Comment by argilo** [comment]
I haven't fixed this yet. I'll update this ticket if I learn anything more.

**Comment by argilo** [comment]
OK, I think I tracked down the problem to a missing trailing slash on the service URL. Once I added that in olsrd.conf the service appeared in AREDN.

**Comment by argilo** [comment]
@mathisono I just pushed a fix that should allow the rest of the AREDN mesh to see the hsmm-pi node's services. Next I'll have to add a path parameter to hsmm-pi.

**Comment by argilo** [comment]
This should be fixed in version 0.7.0.

**Comment by mathisono** [comment]
nice work on the bug fix effort! I oh you a beer! I will give 0.8.0 a run
