### ISSUE TITLE
Request: Use Second WLAN Adapter as Regular 802.11B/G AP with bridged connection to LAN

### ISSUE THREAD

**Issue by ryanturner** [urlgrey/hsmm-pi#7]
Name says it all! Right now it bridges the wired connection, but if we have a second wlan adapter it'd be nice to create an infrastructure ap with the LAN connection bridged, and long term even add the feature to connect to existing APs for WAN connectivity.

**Comment by argilo** [comment]
Let's carry on the discussion in https://github.com/urlgrey/hsmm-pi/issues/25.
