### ISSUE TITLE
Network service does not advertise correct port.

### ISSUE THREAD

**Issue by dandrzejewski** [urlgrey/hsmm-pi#73]
When I add a network service, like so:
![add_network_service](https://cloud.githubusercontent.com/assets/181952/14228844/0d8301b6-f8f0-11e5-8f46-2e1176d6dc20.png)

And save it, it adds it like this:

![screen shot 2016-04-02 at 4 29 36 pm](https://cloud.githubusercontent.com/assets/181952/14228845/1b9e1a1a-f8f0-11e5-929d-6c324d9f84fe.png)

Further, I don't see any port forwarding getting added in iptables.

Am I missing something or is this a bug?

**Comment by argilo** [comment]
That looks correct. The forwarding rule should be written to /etc/rc.local. Is it not working after a reboot?

**Comment by argilo** [comment]
"Port" is the port that is advertised, and "Local Port" is the port that the connection gets forwarded to behind NAT.

**Comment by dandrzejewski** [comment]
Ah. Got it. I had them backwards.  And, also, I was neglecting the "-t nat" when I was listing my iptables output.

I think the labelling on the UI for the ports should be more clear.  Aside from that, all is working well.

**Comment by argilo** [comment]
Any suggestions for the labelling? I just changed the labels because I thought they were unclear before ("forwarding port" for the externally visible port, and "port" for the one behind NAT). I chose the new labels to match the terms my wifi router uses for the same.

**Comment by argilo** [comment]
BTW I'm planning on implementing the 5-host direct & 13-host direct modes soon, which will make NAT unnecessary.
