### ISSUE TITLE
Get rid of callsign announcement?

### ISSUE THREAD

**Issue by argilo** [urlgrey/hsmm-pi#78]
@urlgrey Broadband Hamnet and AREDN don't do separate callsign announcements the way hsmm-pi does, presumably because the convention is to put one's callsign into the node name which is announced very frequently anyway. Do you think it make sense to simplify hsmm-pi by removing the callsign announcement feature?

**Comment by urlgrey** [comment]
That sounds good to me. Including the callsign in an ICMP ping packet
always seemed like a hack; the convention of embedding the call sign in the
node name is preferable.
On Sun, Apr 3, 2016 at 4:04 PM Clayton Smith <notifications@github.com>
wrote:

> @urlgrey <https://github.com/urlgrey> Broadband Hamnet and AREDN don't do
> separate callsign announcements the way hsmm-pi does, presumably because
> the convention is to put one's callsign into the node name which is
> announced very frequently anyway. Do you think it make sense to simplify
> hsmm-pi by removing the callsign announcement feature?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/urlgrey/hsmm-pi/issues/78>
>
-- 
--Scott Kidder

**Comment by argilo** [comment]
OK, I've removed it in my fork and will put that change in the next release: https://github.com/argilo/hsmm-pi/commit/134bbc5777faf988f9d894afd19e90f8985982ae
