### ISSUE TITLE
Error in new version

### ISSUE THREAD

**Issue by shaozhai** [urlgrey/hsmm-pi#80]
![image](https://cloud.githubusercontent.com/assets/3293135/14630304/426501b6-063f-11e6-8f06-ae81d3b0f144.png)

**Comment by argilo** [comment]
@shaozhai Can you provide some further details about when this error appeared? Were you trying to install on top of a fresh Raspbian Jessie install on a Raspberry Pi, or something else?

**Comment by argilo** [comment]
Also, if you could paste the entire output of the install process, that would be very helpful.

**Comment by shaozhai** [comment]
raspberry pi2 debian

**Comment by argilo** [comment]
Was it a fresh install of Raspbian?

Which version of Raspbian were you using? Wheezy or Jessie? What was the release date?

Please paste the full output of the install process.

Without the above information, I can't help.

**Comment by shaozhai** [comment]
Jessie

**Comment by argilo** [comment]
Sorry, you haven't provided enough information to diagnose the issue so there's not much I can do.

**Comment by shaozhai** [comment]
The system did not find this  database file ‘hsmm-pi.sqlite’

**Comment by shaozhai** [comment]
![image](https://cloud.githubusercontent.com/assets/3293135/14839536/2eaa6dee-0c5e-11e6-84ae-2e5fa7c90205.png)

**Comment by shaozhai** [comment]
The new version of the re installation problem is still

**Comment by shaozhai** [comment]
Did not create this file hsmm-pi.sqlite

**Comment by argilo** [comment]
@shaozhai You must start with a fresh install of Debian Jessie.

**Comment by argilo** [comment]
Erase your SD card and start from scratch.

**Comment by shaozhai** [comment]
![image](https://cloud.githubusercontent.com/assets/3293135/14839623/0a7d9260-0c5f-11e6-8aa6-8217baed4b3d.png)

**Comment by shaozhai** [comment]
Have you installed the new HSMM-PI yourself? 0.6 without this problem

**Comment by argilo** [comment]
Yes, many times.

**Comment by shaozhai** [comment]
0.8 there is a problem.

**Comment by shaozhai** [comment]
Can I  manually create this hsmm-pi.sqlite?

**Comment by argilo** [comment]
Erase your SD card, install 2016-03-18-raspbian-jessie-lite, install HSMM-Pi and everything should work fine.

**Comment by shaozhai** [comment]
I try!
