### ISSUE TITLE
Internal Error occured

### ISSUE THREAD

**Issue by sv1** [urlgrey/hsmm-pi#95]
Hello I am getting a Internal Error Occurred when trying to Login, after upgrading php5 to version 5.6.20 through apt-get update on a Debian Jessie.

Any suggestions would be greatly appreciated.

**Comment by sv1** [comment]
This is the error when trying login manually
$ php -f login.ctp 
<div class="users form">
PHP Fatal error:  Using $this when not in object context in /home/pi/hsmm-pi/src/var/www/hsmm-pi/View/Users/login.ctp on line 3

**Comment by cbegg50** [comment]
For internal errors, look in ~/hsrmm-pi/src/var/www/hsmm-pi/logs at error.log, there's a traceback in there.

**Comment by sv1** [comment]
Although shockwave flash plugin is installed on Iceweasel, I get the error below.

2016-05-29 20:47:07 Error: [MissingComponentException] Component class FlashComponent could not be found.
Exception Attributes: array (
  'class' => 'FlashComponent',
  'plugin' => false,
)
Request URL: /hsmm-pi/users/login
Stack Trace:
#0 /usr/share/php/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('Flash', Array)
#1 /usr/share/php/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(UsersController))
#2 /usr/share/php/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /usr/share/php/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /home/pi/hsmm-pi/src/var/www/hsmm-pi/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by argilo** [comment]
@sv1 It looks like you're using Debian's version of CakePHP, which is very outdated. You need to use the version that is installed by `install.sh` (2.8.3).

**Comment by sv1** [comment]
I am using the CakePHP that is installed by install.sh, but it is not 2.8.3.

# cake.php --help

Welcome to CakePHP v2.6.7 Console

**Comment by argilo** [comment]
OK, you need to update to 2.8.3 then. That version is too old.

**Comment by sv1** [comment]
How can I update since pear channel is off???

**Comment by argilo** [comment]
Unfortunately you're stuck for now, until the Pear channel comes back up or we figure out another way to install CakePHP.

**Comment by argilo** [comment]
The pear channel is back up. Are you able to upgrade now?

**Comment by sv1** [comment]
Everything is working as expected. Thank you!!!

please close this issue
