### ISSUE TITLE
Pear Cake PHP channel website is down, project on hold

### ISSUE THREAD

**Issue by cbegg50** [urlgrey/hsmm-pi#96]
Hi, your method of installing Cake PHP relies on the Pear Cake PHP channel and that site is currently down and your install script no longer works.

**Comment by argilo** [comment]
Thanks for reporting that. Let's keep an eye on it, and if the service doesn't soon return we can look at changing the way CakePHP is installed.

**Comment by syelnmh** [comment]
I noticed this issue yesterday, and it drove me crazy (I missed the errors while running install.sh) . I tried manually installing cake 2.8.3, with no luck. The directory structures don't match up. Test.php was not helpful. From my adventures, I see that cake has 3.x.x versions. I don't expect this project to upgrade, but it should be considered?

**Comment by argilo** [comment]
> I don't expect this project to upgrade, but it should be considered?

See issue #85.

**Comment by argilo** [comment]
> I missed the errors while running install.sh

I've had this problem too; probably we should add `set -e` to install.sh so it stops anytime an error occurs. I'll open an issue so we remember to do that.

**Comment by cbegg50** [comment]
I've modified install.sh and used Composer to install Cakephp V2.8.3 and am currently testing it in my fork.  Just let me know if you want me to keep it.

**Comment by argilo** [comment]
Sounds like a good approach, as CakePHP has moved from Pear to Composer in version 3.

**Comment by argilo** [comment]
The pear channel is back up now.

**Comment by syelnmh** [comment]
The pear/cake setup now installs without error.
I did notice an `E: Unable to locate package ifplugd` during install, not sure if that's related.
Also, cake still doesn't seem to work.

The <pi ip>:8080 page on chrome says `The 192.168.1.75 page isn’t working` (same as when cake wasn't installed properly)
navigating to <pi ip>:8080/hsmm-pi/test.php shows the following:

```

Warning: include(Cake/bootstrap.php): failed to open stream: No such file or directory in /home/pi/hsmm-pi/src/var/www/hsmm-pi/webroot/test.php on line 82
```
```
Warning: include(): Failed opening 'Cake/bootstrap.php' for inclusion (include_path='/home/pi/hsmm-pi/src/var/www/lib:.:/usr/share/php:/usr/share/pear') in /home/pi/hsmm-pi/src/var/www/hsmm-pi/webroot/test.php on line 82
```
```
Fatal error: CakePHP core could not be found. Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php. It should point to the directory containing your /cake core directory and your /vendors root directory. in /home/pi/hsmm-pi/src/var/www/hsmm-pi/webroot/test.php on line 91
```

**Comment by argilo** [comment]
@syelnmh Are you running the installer on a freshly flashed Debian Jessie image, or something else?

**Comment by syelnmh** [comment]
Good call. I've reinstalled the OS, works now. (5th reinstall for hsmm-pi, haha)

**Comment by argilo** [comment]
Good to hear.

The installer is built to run on a fresh Raspbian install, and is likely to run into trouble in other situations.
